stages:
  - test

variables:
  DJANGO_SETTINGS_MODULE: "config.settings"

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip
  - python3 -m pip install pip --upgrade
  - python3 -m pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - python -m pip install -r requirements.txt

test:
  stage: test
  script:
    - python3 manage.py test