stages:
  - test

variables:
  DJANGO_SETTINGS_MODULE: "config.settings"

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip python3-venv
  - python3 -m venv venv
  - source venv/bin/activate
  - python -m pip install -r requirements.txt
  - apt-get install -y mysql-client

services:
  - mysql

test:
  stage: test
  script:
    - mysql --version
    - python3 manage.py migrate
    - python3 manage.py test